# Generated by Django 2.0.6 on 2019-01-25 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URLPattern',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longURL', models.CharField(max_length=1000)),
                ('shortURL', models.CharField(max_length=200)),
            ],
        ),
    ]
