# Generated by Django 2.0.6 on 2019-01-25 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('URL', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlpattern',
            name='shortURL',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
