# Generated by Django 2.0.6 on 2019-01-26 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('URL', '0002_auto_20190125_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlpattern',
            name='visits',
            field=models.IntegerField(default=1),
        ),
    ]
