# Generated by Django 2.0.6 on 2019-01-26 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('URL', '0003_urlpattern_visits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlpattern',
            name='visits',
            field=models.IntegerField(default=0),
        ),
    ]
